In [68]:
#     Parameter

steps = 2

In [69]:
import pandas as pd
import numpy as np
from keras.layers import Dense, BatchNormalization, Dropout, LSTM, SimpleRNN, Flatten
from keras.models import Sequential
import keras
import tensorflow
import matplotlib.pyplot as plt
import random as rand

In [70]:
df = pd.read_excel("all_data.xlsx", names=[i for i in range(1,21)])
df

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
0,1000000000000000000000100000000000000000000000...,0100000000000000000000010000000000000000000000...,0010000000000000000000001000000000000000000000...,0001000000000000000000000010000000000000000000...,0000100000000000000000000001000000000000000000...,0000010000000000000000000000000001000000000000...,0000001000000000000000000000000000001000000000...,0000000100000000000000000000000000000010000000...,0000000010000000000000000000000000000001000000...,0000000001000000000000000000000000000000000100...,0000000000100000000000000000000000000000000000...,0000000000010000000000000000000000000000000000...,0000000000001000000000000000000000000000000000...,0000000000000100000000000000000000000000000000...,0000000000000010000000000000000000000000000000...,0000000000000001000000000000000000000000000000...,0000000000000000100000000000000000000000000000...,0000000000000000010000000000000000000000000000...,0000000000000000001000000000000000000000000000...,0000000000000000000100000000000000000000000000...
1,1000000000000000000000010000000000000000000000...,0100000000000000000000000010000000000000000000...,0010000000000000000000000000010000000000000000...,0001000000000000000000000000000000000000001000...,0000100000000000000000000000000000000000000010...,0000010000000000000000000000000000000000000001...,0000001000000000000000000000000000000000000000...,0000000100000000000000000000000000000000000000...,0000000010000000000000000000000000000000000000...,0000000001000000000000000000000000000000000000...,0000000000100000000000000000000000000000000000...,0000000000010000000000000000000000000000000000...,0000000000001000000000000000000000000000000000...,0000000000000100000000000000000000000000000000...,0000000000000010000000000000000000000000000000...,0000000000000001000000000000000000000000000000...,0000000000000000100000000000000000000000000000...,0000000000000000010000000000000000000000000000...,0000000000000000001000000000000000000000000000...,0000000000000000000100000000000000000000000000...
2,1000000000000000000000100000000000000000000000...,0100000000000000000000000000001000000000000000...,0010000000000000000000000000000000000010000000...,0001000000000000000000000000000000000000000010...,0000100000000000000000000000000000000000000000...,0000010000000000000000000000000000000000000000...,0000001000000000000000000000000000000000000000...,0000000100000000000000000000000000000000000000...,0000000010000000000000000000000000000000000000...,0000000001000000000000000000000000000000000000...,0000000000100000000000000000000000000000000000...,0000000000010000000000000000000000000000000000...,0000000000001000000000000000000000000000000000...,0000000000000100000000000000000000000000000000...,0000000000000010000000000000000000000000000000...,0000000000000001000000000000000000000000000000...,0000000000000000100000000000000000000000000000...,0000000000000000010000000000000000000000000000...,0000000000000000001000000000000000000000000000...,0000000000000000000100000000000000000000000000...
3,1000000000000000000000100000000000000000000000...,0100000000000000000000010000000000000000000000...,0010000000000000000000000000100000000000000000...,0001000000000000000000000000000000100000000000...,0000100000000000000000000000000000010000000000...,0000010000000000000000000000000000000000000000...,0000001000000000000000000000000000000000000000...,0000000100000000000000000000000000000000000000...,0000000010000000000000000000000000000000000000...,0000000001000000000000000000000000000000000000...,0000000000100000000000000000000000000000000000...,0000000000010000000000000000000000000000000000...,0000000000001000000000000000000000000000000000...,0000000000000100000000000000000000000000000000...,0000000000000010000000000000000000000000000000...,0000000000000001000000000000000000000000000000...,0000000000000000100000000000000000000000000000...,0000000000000000010000000000000000000000000000...,0000000000000000001000000000000000000000000000...,0000000000000000000100000000000000000000000000...
4,1000000000000000000000100000000000000000000000...,0100000000000000000000000000001000000000000000...,0010000000000000000000000000000010000000000000...,0001000000000000000000000000000001000000000000...,0000100000000000000000000000000000001000000000...,0000010000000000000000000000000000000010000000...,0000001000000000000000000000000000000000000010...,0000000100000000000000000000000000000000000000...,0000000010000000000000000000000000000000000000...,0000000001000000000000000000000000000000000000...,0000000000100000000000000000000000000000000000...,0000000000010000000000000000000000000000000000...,0000000000001000000000000000000000000000000000...,0000000000000100000000000000000000000000000000...,0000000000000010000000000000000000000000000000...,0000000000000001000000000000000000000000000000...,0000000000000000100000000000000000000000000000...,0000000000000000010000000000000000000000000000...,0000000000000000001000000000000000000000000000...,0000000000000000000100000000000000000000000000...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9141,1000000000000000000000010000000000000000000000...,0100000000000000000000000010000000000000000000...,0010000000000000000000000000010000000000000000...,0001000000000000000000000000000010000000000000...,0000100000000000000000000000000000100000000000...,0000010000000000000000000000000000010000000000...,0000001000000000000000000000000000001000000000...,0000000100000000000000000000000000000010000000...,0000000010000000000000000000000000000000010000...,0000000001000000000000000000000000000000000000...,0000000000100000000000000000000000000000000000...,0000000000010000000000000000000000000000000000...,0000000000001000000000000000000000000000000000...,0000000000000100000000000000000000000000000000...,0000000000000010000000000000000000000000000000...,0000000000000001000000000000000000000000000000...,0000000000000000100000000000000000000000000000...,0000000000000000010000000000000000000000000000...,0000000000000000001000000000000000000000000000...,0000000000000000000100000000000000000000000000...
9142,1000000000000000000010000000000000000000000000...,0100000000000000000000010000000000000000000000...,0010000000000000000000000000100000000000000000...,0001000000000000000000000000010000000000000000...,0000100000000000000000000000000001000000000000...,0000010000000000000000000000000000000001000000...,0000001000000000000000000000000000000000000010...,0000000100000000000000000000000000000000000000...,0000000010000000000000000000000000000000000000...,0000000001000000000000000000000000000000000000...,0000000000100000000000000000000000000000000000...,0000000000010000000000000000000000000000000000...,0000000000001000000000000000000000000000000000...,0000000000000100000000000000000000000000000000...,0000000000000010000000000000000000000000000000...,0000000000000001000000000000000000000000000000...,0000000000000000100000000000000000000000000000...,0000000000000000010000000000000000000000000000...,0000000000000000001000000000000000000000000000...,0000000000000000000100000000000000000000000000...
9143,1000000000000000000010000000000000000000000000...,0100000000000000000000000010000000000000000000...,0010000000000000000000000001000000000000000000...,0001000000000000000000000000000001000000000000...,0000100000000000000000000000000000100000000000...,0000010000000000000000000000000000000000000010...,0000001000000000000000000000000000000000000000...,0000000100000000000000000000000000000000000000...,0000000010000000000000000000000000000000000000...,0000000001000000000000000000000000000000000000...,0000000000100000000000000000000000000000000000...,0000000000010000000000000000000000000000000000...,0000000000001000000000000000000000000000000000...,0000000000000100000000000000000000000000000000...,0000000000000010000000000000000000000000000000...,0000000000000001000000000000000000000000000000...,0000000000000000100000000000000000000000000000...,0000000000000000010000000000000000000000000000...,0000000000000000001000000000000000000000000000...,0000000000000000000100000000000000000000000000...
9144,1000000000000000000010000000000000000000000000...,0100000000000000000000100000000000000000000000...,0010000000000000000000000001000000000000000000...,0001000000000000000000000000000010000000000000...,0000100000000000000000000000000001000000000000...,0000010000000000000000000000000000000100000000...,0000001000000000000000000000000000000010000000...,0000000100000000000000000000000000000000010000...,0000000010000000000000000000000000000000000001...,0000000001000000000000000000000000000000000000...,0000000000100000000000000000000000000000000000...,0000000000010000000000000000000000000000000000...,0000000000001000000000000000000000000000000000...,0000000000000100000000000000000000000000000000...,0000000000000010000000000000000000000000000000...,0000000000000001000000000000000000000000000000...,0000000000000000100000000000000000000000000000...,0000000000000000010000000000000000000000000000...,0000000000000000001000000000000000000000000000...,0000000000000000000100000000000000000000000000...
9145,1000000000000000000000000100000000000000000000...,0100000000000000000000000000100000000000000000...,0010000000000000000000000000010000000000000000...,0001000000000000000000000000000010000000000000...,0000100000000000000000000000000000001000000000...,0000010000000000000000000000000000000000010000...,0000001000000000000000000000000000000000000010...,0000000100000000000000000000000000000000000000...,0000000010000000000000000000000000000000000000...,0000000001000000000000000000000000000000000000...,0000000000100000000000000000000000000000000000...,0000000000010000000000000000000000000000000000...,0000000000001000000000000000000000000000000000...,0000000000000100000000000000000000000000000000...,0000000000000010000000000000000000000000000000...,0000000000000001000000000000000000000000000000...,0000000000000000100000000000000000000000000000...,0000000000000000010000000000000000000000000000...,0000000000000000001000000000000000000000000000...,0000000000000000000100000000000000000000000000...

In [71]:
library = pd.read_excel("Library.xlsx", names=["Values"])
library

                                                 Values
0     1000000000000000000010000000000000000000000000...
1     1000000000000000000001000000000000000000000000...
2     1000000000000000000000100000000000000000000000...
3     1000000000000000000000010000000000000000000000...
4     1000000000000000000000001000000000000000000000...
...                                                 ...
1215  0000000000000000000100000000000000000000000000...
1216  0000000000000000000100000000000000000000000000...
1217  0000000000000000000100000000000000000000000000...
1218  0000000000000000000100000000000000000000000000...
1219  0000000000000000000100000000000000000000000000...

[1220 rows x 1 columns]

In [72]:
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

In [73]:
lb = LabelEncoder()
lb.fit(library["Values"])
library["Values"] = lb.transform(library["Values"])
for i in df.columns:
  df[i] = lb.transform(df[i])
df

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
0,1217,1156,1095,1033,972,906,843,781,720,656,593,532,469,407,337,275,206,145,73,11
1,1216,1153,1090,1017,955,894,832,768,697,635,573,507,442,380,311,248,186,124,62,0
2,1217,1149,1081,1015,953,891,830,764,698,635,573,509,442,374,312,251,185,124,62,1
3,1217,1156,1091,1025,964,889,827,766,702,640,578,517,450,384,321,258,196,134,70,3
4,1217,1149,1087,1026,963,901,835,773,711,648,584,502,441,376,314,250,187,126,65,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9141,1216,1153,1090,1027,965,904,843,781,718,652,584,522,461,396,330,269,208,145,81,13
9142,1219,1156,1091,1030,966,900,835,770,706,645,583,520,459,389,327,264,198,134,65,4
9143,1219,1153,1092,1026,965,895,826,763,702,638,571,506,443,381,313,252,190,129,67,1
9144,1219,1157,1092,1027,966,902,841,778,714,650,584,507,443,382,313,252,191,128,63,1
9145,1214,1151,1090,1027,963,898,835,769,708,643,582,521,456,394,332,271,202,138,70,9

In [74]:
X = np.array(df)
test = []
for i in range(steps,9146):
  test.append(X[i, :])
test = np.array(test)
test.shape

(9144, 20)

In [75]:
re = []
for i in test:
  temp = np.zeros(1220)
  for j in i:
    temp[j] = 1
  re.append(temp)
re = np.array(re)
re.shape

(9144, 1220)

In [76]:
sc = MinMaxScaler(feature_range=(0,1))
df = sc.fit_transform(df)
X = np.array(df)
train = []
for i in range(steps,9146):
  train.append(X[i-steps:i, :])
train = np.array(train)

In [77]:
model = Sequential()

model.add(LSTM(units=100, return_sequences=True, input_shape=(train.shape[1],20)))
model.add(LSTM(units=75, return_sequences=True))
model.add(LSTM(units=50, return_sequences=True))
model.add(Flatten())
model.add(Dense(1024, activation="relu"))
model.add(Dense(512, activation="relu"))
model.add(Dense(1220, activation="sigmoid"))

model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])
model.build()
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm_9 (LSTM)               (None, 2, 100)            48400

 lstm_10 (LSTM)              (None, 2, 75)             52800

 lstm_11 (LSTM)              (None, 2, 50)             25200

 flatten_3 (Flatten)         (None, 100)               0

 dense_9 (Dense)             (None, 1024)              103424

 dense_10 (Dense)            (None, 512)               524800

 dense_11 (Dense)            (None, 1220)              625860

=================================================================
Total params: 1,380,484
Trainable params: 1,380,484
Non-trainable params: 0
_________________________________________________________________

In [78]:
from sklearn.model_selection import train_test_split

In [79]:
x_train, x_test, y_train, y_test = train_test_split(train, re, train_size=0.8)
x_train.shape, y_train.shape

((7315, 2, 20), (7315, 1220))

In [ ]:
history = model.fit(x_train, y_train, epochs=100, validation_split=0.1, batch_size=32)

Epoch 1/100
206/206 [==============================] - 43s 37ms/step - loss: 0.1249 - accuracy: 0.1027 - val_loss: 0.0684 - val_accuracy: 0.2486
Epoch 2/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0680 - accuracy: 0.0997 - val_loss: 0.0681 - val_accuracy: 0.2486
Epoch 3/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0678 - accuracy: 0.1209 - val_loss: 0.0679 - val_accuracy: 0.0000e+00
Epoch 4/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0676 - accuracy: 0.0924 - val_loss: 0.0678 - val_accuracy: 0.1926
Epoch 5/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0675 - accuracy: 0.1196 - val_loss: 0.0678 - val_accuracy: 0.0000e+00
Epoch 6/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0675 - accuracy: 0.1340 - val_loss: 0.0679 - val_accuracy: 0.0000e+00
Epoch 7/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0675 - accuracy: 0.1186 - val_loss: 0.0678 - val_accuracy: 0.0000e+00
Epoch 8/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0674 - accuracy: 0.1075 - val_loss: 0.0678 - val_accuracy: 0.0000e+00
Epoch 9/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0674 - accuracy: 0.1001 - val_loss: 0.0677 - val_accuracy: 0.0000e+00
Epoch 10/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0674 - accuracy: 0.1021 - val_loss: 0.0678 - val_accuracy: 0.0000e+00
Epoch 11/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0674 - accuracy: 0.0989 - val_loss: 0.0677 - val_accuracy: 0.2486
Epoch 12/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0674 - accuracy: 0.1325 - val_loss: 0.0677 - val_accuracy: 0.0000e+00
Epoch 13/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0673 - accuracy: 0.1021 - val_loss: 0.0677 - val_accuracy: 0.2486
Epoch 14/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0673 - accuracy: 0.1126 - val_loss: 0.0677 - val_accuracy: 0.2486
Epoch 15/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0673 - accuracy: 0.1353 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 16/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0673 - accuracy: 0.1243 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 17/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0673 - accuracy: 0.0880 - val_loss: 0.0677 - val_accuracy: 0.2486
Epoch 18/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0673 - accuracy: 0.1203 - val_loss: 0.0676 - val_accuracy: 0.2486
Epoch 19/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0673 - accuracy: 0.0955 - val_loss: 0.0677 - val_accuracy: 0.0000e+00
Epoch 20/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0673 - accuracy: 0.0974 - val_loss: 0.0677 - val_accuracy: 0.2486
Epoch 21/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0673 - accuracy: 0.1013 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 22/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0673 - accuracy: 0.1054 - val_loss: 0.0676 - val_accuracy: 0.2486
Epoch 23/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0673 - accuracy: 0.1012 - val_loss: 0.0676 - val_accuracy: 0.2486
Epoch 24/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0673 - accuracy: 0.0992 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 25/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0673 - accuracy: 0.1379 - val_loss: 0.0676 - val_accuracy: 0.2486
Epoch 26/100
206/206 [==============================] - 7s 32ms/step - loss: 0.0673 - accuracy: 0.1039 - val_loss: 0.0675 - val_accuracy: 0.0000e+00
Epoch 27/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0673 - accuracy: 0.1341 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 28/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0673 - accuracy: 0.0943 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 29/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0673 - accuracy: 0.0884 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 30/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0672 - accuracy: 0.1006 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 31/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0673 - accuracy: 0.0977 - val_loss: 0.0676 - val_accuracy: 0.2486
Epoch 32/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0673 - accuracy: 0.1045 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 33/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0905 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 34/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0672 - accuracy: 0.1118 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 35/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0672 - accuracy: 0.0980 - val_loss: 0.0676 - val_accuracy: 0.2486
Epoch 36/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0793 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 37/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0934 - val_loss: 0.0677 - val_accuracy: 0.0000e+00
Epoch 38/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0997 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 39/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0966 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 40/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0672 - accuracy: 0.0987 - val_loss: 0.0676 - val_accuracy: 0.2486
Epoch 41/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0672 - accuracy: 0.0997 - val_loss: 0.0676 - val_accuracy: 0.1926
Epoch 42/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0881 - val_loss: 0.0676 - val_accuracy: 0.2486
Epoch 43/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.1039 - val_loss: 0.0676 - val_accuracy: 0.2486
Epoch 44/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.1136 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 45/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0816 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 46/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0886 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 47/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.1030 - val_loss: 0.0676 - val_accuracy: 0.2486
Epoch 48/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0672 - accuracy: 0.1215 - val_loss: 0.0675 - val_accuracy: 0.0000e+00
Epoch 49/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0875 - val_loss: 0.0676 - val_accuracy: 0.2486
Epoch 50/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.1250 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 51/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0939 - val_loss: 0.0675 - val_accuracy: 0.0000e+00
Epoch 52/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0761 - val_loss: 0.0675 - val_accuracy: 0.0000e+00
Epoch 53/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0899 - val_loss: 0.0675 - val_accuracy: 0.0000e+00
Epoch 54/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0672 - accuracy: 0.1113 - val_loss: 0.0676 - val_accuracy: 0.2486
Epoch 55/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0804 - val_loss: 0.0675 - val_accuracy: 0.2486
Epoch 56/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.1092 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 57/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0672 - accuracy: 0.1056 - val_loss: 0.0676 - val_accuracy: 0.2486
Epoch 58/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.1127 - val_loss: 0.0675 - val_accuracy: 0.0000e+00
Epoch 59/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0664 - val_loss: 0.0675 - val_accuracy: 0.0000e+00
Epoch 60/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0986 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 61/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0965 - val_loss: 0.0675 - val_accuracy: 0.2486
Epoch 62/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.1075 - val_loss: 0.0675 - val_accuracy: 0.0000e+00
Epoch 63/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0966 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 64/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0914 - val_loss: 0.0675 - val_accuracy: 0.0000e+00
Epoch 65/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0955 - val_loss: 0.0675 - val_accuracy: 0.0000e+00
Epoch 66/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0843 - val_loss: 0.0675 - val_accuracy: 0.0000e+00
Epoch 67/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0872 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 68/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0672 - accuracy: 0.0887 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 69/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0672 - accuracy: 0.0570 - val_loss: 0.0675 - val_accuracy: 0.0178
Epoch 70/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0671 - accuracy: 0.0972 - val_loss: 0.0676 - val_accuracy: 0.0027
Epoch 71/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0671 - accuracy: 0.1027 - val_loss: 0.0675 - val_accuracy: 0.0000e+00
Epoch 72/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0671 - accuracy: 0.0877 - val_loss: 0.0676 - val_accuracy: 0.2486
Epoch 73/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0671 - accuracy: 0.0960 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 74/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0671 - accuracy: 0.0960 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 75/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0671 - accuracy: 0.1158 - val_loss: 0.0675 - val_accuracy: 0.0000e+00
Epoch 76/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0671 - accuracy: 0.1003 - val_loss: 0.0675 - val_accuracy: 0.0000e+00
Epoch 77/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0671 - accuracy: 0.1095 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 78/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0671 - accuracy: 0.1095 - val_loss: 0.0675 - val_accuracy: 0.0000e+00
Epoch 79/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0671 - accuracy: 0.0887 - val_loss: 0.0676 - val_accuracy: 0.0260
Epoch 80/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0671 - accuracy: 0.1086 - val_loss: 0.0675 - val_accuracy: 0.0000e+00
Epoch 81/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0670 - accuracy: 0.1074 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 82/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0670 - accuracy: 0.0969 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 83/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0670 - accuracy: 0.0910 - val_loss: 0.0676 - val_accuracy: 0.1516
Epoch 84/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0670 - accuracy: 0.1028 - val_loss: 0.0675 - val_accuracy: 0.0232
Epoch 85/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0670 - accuracy: 0.1387 - val_loss: 0.0676 - val_accuracy: 0.0000e+00
Epoch 86/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0670 - accuracy: 0.0922 - val_loss: 0.0676 - val_accuracy: 0.1803
Epoch 87/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0670 - accuracy: 0.1302 - val_loss: 0.0676 - val_accuracy: 0.0055
Epoch 88/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0670 - accuracy: 0.0930 - val_loss: 0.0676 - val_accuracy: 0.1421
Epoch 89/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0669 - accuracy: 0.1079 - val_loss: 0.0676 - val_accuracy: 0.0055
Epoch 90/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0669 - accuracy: 0.1069 - val_loss: 0.0676 - val_accuracy: 0.0410
Epoch 91/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0669 - accuracy: 0.1109 - val_loss: 0.0676 - val_accuracy: 0.1885
Epoch 92/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0669 - accuracy: 0.0936 - val_loss: 0.0677 - val_accuracy: 0.1762
Epoch 93/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0669 - accuracy: 0.1165 - val_loss: 0.0677 - val_accuracy: 0.0219
Epoch 94/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0668 - accuracy: 0.0933 - val_loss: 0.0677 - val_accuracy: 0.2281
Epoch 95/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0668 - accuracy: 0.1117 - val_loss: 0.0678 - val_accuracy: 0.1981
Epoch 96/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0668 - accuracy: 0.1162 - val_loss: 0.0677 - val_accuracy: 0.0710
Epoch 97/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0668 - accuracy: 0.1066 - val_loss: 0.0678 - val_accuracy: 0.0505
Epoch 98/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0667 - accuracy: 0.1068 - val_loss: 0.0678 - val_accuracy: 0.1721
Epoch 99/100
206/206 [==============================] - 6s 31ms/step - loss: 0.0667 - accuracy: 0.1253 - val_loss: 0.0678 - val_accuracy: 0.0369
Epoch 100/100
206/206 [==============================] - 6s 30ms/step - loss: 0.0667 - accuracy: 0.1010 - val_loss: 0.0679 - val_accuracy: 0.1995

In [ ]:
plt.plot(history.history["loss"])
plt.plot(history.history["accuracy"])
plt.title("Step = 5")
plt.ylim(0, 1)
plt.show()

In [ ]:
predict = model.predict(x_test)
predict.shape

In [ ]:
model.evaluate(x_test, y_test)

In [ ]:
plt.plot([max(np.argpartition(i, -20)[-20:]) for i in y_test[0:100]], color='red', label="sum of Real values")
plt.plot([max(np.argpartition(i, -20)[-20:]) for i in predict[0:100]], color='blue', label="sum of predicted values")
plt.title("Model Result")
plt.show()

In [ ]:
#plt.plot([sum(np.argpartition(i, -20)[-20:]) for i in y_test], color='red', label="sum of Real values")
plt.plot([np.mean(np.argpartition(i, -20)[-20:]) for i in predict[0:100]], color='blue', label="sum of predicted values")
plt.title("Model Result")
plt.show()

In [ ]:
max(np.argpartition(predict[0], -20)[-20:])